info:
  version: 1.0
  name: provider


server:
  port: 8081
spring:
  application:
    name: provider
  zipkin:
    enabled: true
    base-url: http://10.0.0.5:9411
  sleuth:
    sampler:
      probability: 1


eureka:
  client:
    service-url:
      default-zone: http://192.168.1.105:8761/eureka/
