// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.demo.grpc.api;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
