server:
  port: 8761

eureka:
  instance:
    hostname: jmbkeyes
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false
    serviceUrl:
      defaultZone: http://10.0.0.5:8761/eureka/

