info:
  version: 1.0
  name: hello-rpc-server

server:
  port: 8082
spring:
  application:
    name: hello-grpc-server
  zipkin:
    enabled: true
    #base-url: http://10.0.0.5:9411
    sender:
      type: kafka
    kafka:
      topic: zipkin
  kafka:
    bootstrap-servers: 10.0.0.5:9090,10.0.0.5:9091,10.0.0.5:9092
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    service-url:
      default-zone: http://10.0.0.5:8761/eureka/
grpc:
  server:
    port: 7070
