info:
  version: 1.0
  name: grpc-client


server:
  port: 8012

grpc:
  client:
    hello-grpc-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
eureka:
  client:
    service-url:
      default-zone: http://10.0.0.5:8761/eureka/
spring:
  application:
    name: grpc-client
  zipkin:
    enabled: true
    base-url: http://10.0.0.5:9411
  sleuth:
    sampler:
      probability: 1